apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployments.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.deployments.spec.containerPort }}
      protocol: TCP
  type: NodePort
  selector:
    app: {{ .Values.deployments.name }}
